apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: spark-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spark-worker
  minReplicas: 1
  maxReplicas: 40
  targetCPUUtilizationPercentage: 50 # target CPU utilization 
