kind: StatefulSet 
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  serviceName: spark-master 
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          imagePullPolicy: Always
          image: "{{ .Values.image }}"
          env:
            - name: "STORAGE_KEY"
              value: "{{ .Values.storage_key }}"
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 1500m
              memory: 7Gi
      imagePullSecrets:
        - name: acr-creds
      nodeSelector:
        agentpool: default
