kind: StatefulSet 
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  serviceName: spark-master 
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          imagePullPolicy: Always
          image: "{{ .Values.image }}" 
          command: ["/spark-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 1800m
      imagePullSecrets:
        - name: acr-creds
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Exists"
