kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-worker
spec:
  replicas: {{ .Values.spark_replicas }} 
  selector:
    matchLabels:
      component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      containers:
        - name: spark-worker
          imagePullPolicy: Always
          image: "{{ .Values.image }}" 
          env:
            - name: "STORAGE_KEY"
              value: "{{ .Values.storage_key }}"
          command: ["/spark-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 1400m
              memory: 4Gi
      imagePullSecrets:
        - name: acr-creds
      nodeSelector:
        agentpool: compute
      tolerations:
        - key: kubernetes.azure.com/scalesetpriority
          operator: "Exists"
